name: Deploy to Siteground - HallOfDoom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio en la máquina del runner
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pruebas consola
        run: |
          pwd
          ls -la