name: Deploy to Siteground - HallOfDoom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio en la máquina del runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Configurar Angular CLI
      - name: Setup Angular CLI
        run: npm install -g @angular/cli

      # Instalar dependencias del proyecto
      - name: Install Dependencies
        run: npm install

      #Build del proyecto
      - name: Build Angular Project
        run: ng build

      # Pruebas de consola
      - name: Pruebas consola
        run: |
          pwd
          ls -la
          